### ISSUE TITLE
Bug - return value + input value

### ISSUE THREAD

**Issue by eyeskiller** [BeHappyCommunication/SyliusManufacturerPlugin#1]
Hi I just installed this plugin, and i had my own Entity override already created, so I added functions from vendor to my custom Entity, and I getting this error.

```
The return type of method "getManufacturer" in class "App\Entity\Product\Product" is invalid.
```

```PHP
<?php

declare(strict_types=1);

namespace App\Entity\Product;

use Doctrine\ORM\Mapping\MappedSuperclass;
use Doctrine\ORM\Mapping\Table;
use Sylius\Component\Core\Model\Product as BaseProduct;
use Sylius\Component\Core\Model\ProductInterface;
use Sylius\Component\Product\Model\ProductTranslationInterface;

/**
 * @MappedSuperclass
 * @Table(name="sylius_product")
 */
class Product extends BaseProduct implements ProductInterface
{
    protected function createTranslation(): ProductTranslationInterface
    {
        return new ProductTranslation();
    }

    /** @var ManufacturerInterface|null */
    protected $manufacturer;

    /**
     * @return ManufacturerInterface|null
     */
    public function getManufacturer(): ?ManufacturerInterface
    {
        return $this->manufacturer;
    }

    /**
     * @param ManufacturerInterface|null $manufacturer
     */
    public function setManufacturer(?ManufacturerInterface $manufacturer): void
    {
        $this->manufacturer = $manufacturer;
    }
}
```

**Comment by Roshyo** [comment]
You need to import the namespace as well `use BeHappy\SyliusManufacturerPlugin\Entity\ManufacturerInterface;` Because your custom entity is in a new Namespace.

**Comment by igormukhingmailcom** [comment]
Core entities (resources) should be provided just as interface+trait with annotation mapping.
Otherwise this plugin will fail on any app that already have plugin overriding same core entity (resource).

**Comment by Roshyo** [comment]
Yes indeed that's the recomended way since early 2019. But this plugin was written in july 2018 and we barely have the time to maintain it. Furthermore, we are thinking to deprecate this plugin in favor of https://github.com/loevgaard/SyliusBrandPlugin
